spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruitdb?useSSL=false
    username: root
    password: 202517
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.study.admin.*
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3